title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://bnussbau.github.io/trmnl-byos-laravel-docs

aux_links:
  Template Repository: https://github.com/bnussbau/trmnl-byos-laravel-docs
